# Generated by Django 6.0.3 on 2026-03-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('code', models.CharField(max_length=2, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/%Y/%m', verbose_name='file')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('music', 'Music')], max_length=30, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('customer_name', models.CharField(max_length=200, verbose_name='customer name')),
                ('customer_position', models.CharField(max_length=200, verbose_name='customer position')),
                ('customer_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_images', to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='OurInstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_link', models.URLField(verbose_name='story link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stories', to='common.media')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=200, verbose_name='home title')),
                ('home_subtitle', models.CharField(max_length=200, verbose_name='home subtitle')),
                ('home_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_images', to='common.media')),
            ],
        ),
    ]
